using UnityEngine;
using System.Collections.Generic;

/// <summary>
/// WorldGenerator — procedurally fills every grid cell with a ground tile sprite on startup.
///
/// SCENE SETUP:
///   1. Create a new empty GameObject named "WorldGenerator" in your scene.
///   2. Add this component to it.
///   3. Assign the fields in the Inspector (WorldGrid is a singleton, assigned automatically).
///   4. Create a TilePrefab: GameObject → 2D Object → Sprite → drag to Project → delete from scene.
///      Set its Sorting Layer to "Ground" and Order in Layer to -10.
///   5. Create TileData assets (Right-click → Create → SawyersSawmill → TileData) for each
///      tile variant and assign them to the appropriate lists below.
///   6. Hit Play — tiles are generated once at startup and never move.
///
/// HOW IT WORKS:
///   • Grass tiles fill every cell as the base layer.
///   • Dirt patches are driven by Perlin noise so they cluster naturally.
///   • Decorations (rocks, branches, flowers) are a second Perlin pass layered on top.
///   • The forest reserve zone (leftmost N columns) stays plain grass so trees look clean.
///   • Obstacle cells (Water, Boulder, OldGrowthTree) get a matching visual tile if you
///     populate riverTiles / boulderTiles, otherwise they are left blank (the obstacle
///     generation in WorldGrid already placed them — this just adds visuals).
///   • Sorting order: ground tiles = -10, decoration tiles = -9 (drawn above base).
/// </summary>
public class WorldGenerator : MonoBehaviour
{
    // ── References ────────────────────────────────────────────────────────────

    [Header("References")]
    [Tooltip("Simple prefab with only a SpriteRenderer. Set Sorting Layer = Ground, Order = -10.")]
    public GameObject tilePrefab;

    // WorldGrid.Instance is available after its Awake — we grab it in our own Awake.
    // Execution order: WorldGrid must Awake BEFORE WorldGenerator.
    // Set this in Edit → Project Settings → Script Execution Order:
    //   WorldGrid = -100, WorldGenerator = -90

    // ── Tile Sets ──────────────────────────────────────────────────────────────

    [Header("Ground Tiles")]
    [Tooltip("Base grass variants. At least one entry required.")]
    public List<TileData> grassTiles = new List<TileData>();

    [Tooltip("Bare dirt patches. Used when Perlin noise exceeds dirtThreshold.")]
    public List<TileData> dirtTiles = new List<TileData>();

    [Header("Decoration Tiles (layered on top of grass)")]
    [Tooltip("Small rocks, fallen branches, wildflowers — scattered via a second noise pass.")]
    public List<TileData> decorationTiles = new List<TileData>();

    [Header("Obstacle Visual Tiles (optional — match WorldGrid obstacle generation)")]
    [Tooltip("Visual tile placed on Water cells generated by WorldGrid. Can be left empty.")]
    public List<TileData> riverTiles = new List<TileData>();

    [Tooltip("Visual tile placed on Boulder cells generated by WorldGrid. Can be left empty.")]
    public List<TileData> boulderTiles = new List<TileData>();

    [Tooltip("Visual tile placed on OldGrowthTree cells. Can be left empty.")]
    public List<TileData> oldGrowthTiles = new List<TileData>();

    // ── Generation Settings ────────────────────────────────────────────────────

    [Header("Zone Settings")]
    [Tooltip("How many columns from the LEFT are reserved as the forest zone. " +
             "These cells get plain grass only — no dirt or decorations — so planted trees look clean. " +
             "Match this to ForestZone.forestColumns in your ForestZone component.")]
    public int forestReserveColumns = 6;

    [Header("Noise Settings")]
    [Tooltip("Perlin noise scale for dirt patches. Lower = larger patches, higher = more scattered.")]
    [Range(0.1f, 1f)]
    public float dirtNoiseScale = 0.3f;

    [Tooltip("Perlin noise threshold for dirt patches. " +
             "A cell becomes dirt when noise > (1 - this value). " +
             "0.08 = roughly 8% of cells. Noise clusters mean actual coverage is organic, not uniform.")]
    [Range(0f, 0.4f)]
    public float dirtThreshold = 0.08f;

    [Tooltip("Perlin noise scale for decorations. Higher frequency = more scattered individual pieces.")]
    [Range(0.1f, 2f)]
    public float decorNoiseScale = 0.7f;

    [Tooltip("Perlin noise threshold for decorations (rocks, branches, flowers). " +
             "0.15 = roughly 15% of non-dirt cells get a decoration.")]
    [Range(0f, 0.4f)]
    public float decorThreshold = 0.15f;

    [Tooltip("Offsets the Perlin sample so dirt and decoration noise patterns don't overlap. " +
             "Change this if dirt and decorations feel too correlated.")]
    public float decorNoiseOffset = 100f;

    [Header("Random Seed")]
    [Tooltip("0 = new random world every run. Set a fixed value for a reproducible layout. " +
             "Note: WorldGrid uses its own obstacleSeed for boulders/rivers — this seed " +
             "controls only tile visual variation.")]
    public int seed = 0;

    // ── Sorting Orders ────────────────────────────────────────────────────────

    [Header("Sorting")]
    [Tooltip("Sorting order for base ground tiles (grass, dirt). Should be the lowest value.")]
    public int groundSortingOrder = -10;

    [Tooltip("Sorting order for decoration tiles drawn on top of ground. " +
             "Must be higher than groundSortingOrder.")]
    public int decorSortingOrder = -9;

    // ── Internal ───────────────────────────────────────────────────────────────
    private Transform _tileParent;

    // ──────────────────────────────────────────────────────────────────────────
    private void Awake()
    {
        // Seed the random state for tile variation
        // (WorldGrid obstacle positions use their own separate seed)
        int resolvedSeed = seed != 0 ? seed : System.DateTime.Now.Millisecond * 1000 + System.DateTime.Now.Second;
        Random.InitState(resolvedSeed);

        // Safety check
        if (tilePrefab == null)
        {
            Debug.LogError("[WorldGenerator] tilePrefab is not assigned! " +
                           "Create a simple SpriteRenderer prefab and assign it.");
            return;
        }

        if (grassTiles == null || grassTiles.Count == 0)
        {
            Debug.LogError("[WorldGenerator] grassTiles list is empty! " +
                           "Add at least one TileData asset to the Grass Tiles list.");
            return;
        }

        if (WorldGrid.Instance == null)
        {
            Debug.LogError("[WorldGenerator] WorldGrid.Instance is null! " +
                           "Make sure WorldGrid Awakes before WorldGenerator. " +
                           "Set Script Execution Order: WorldGrid = -100, WorldGenerator = -90.");
            return;
        }

        _tileParent = new GameObject("WorldTiles").transform;
        _tileParent.SetParent(null); // keep hierarchy clean, not a child of WorldGenerator

        GenerateWorld();
    }

    // ── World Generation ──────────────────────────────────────────────────────

    private void GenerateWorld()
    {
        WorldGrid grid = WorldGrid.Instance;
        int cols = grid.Columns;
        int rows = grid.Rows;

        for (int row = 0; row < rows; row++)
        {
            for (int col = 0; col < cols; col++)
            {
                GridCell cell = grid.GetCell(col, row);
                Vector3 worldPos = grid.GridToWorld(col, row, 0f);

                // ── Obstacle cells: place matching visual tile if lists are populated ──
                if (cell.cellType == CellType.Water)
                {
                    SpawnTileFromList(worldPos, riverTiles, groundSortingOrder, col, row);
                    continue;
                }
                if (cell.cellType == CellType.Boulder)
                {
                    SpawnTileFromList(worldPos, boulderTiles, groundSortingOrder, col, row);
                    continue;
                }
                if (cell.cellType == CellType.OldGrowthTree)
                {
                    // Always put grass underneath old growth, then the tree visual on top
                    SpawnTileFromList(worldPos, grassTiles, groundSortingOrder, col, row);
                    SpawnTileFromList(worldPos, oldGrowthTiles, decorSortingOrder, col, row);
                    continue;
                }

                // ── Normal empty cells ─────────────────────────────────────────────

                // Forest reserve zone — plain grass only, keeps tree planting area clean
                if (col < forestReserveColumns)
                {
                    SpawnTileFromList(worldPos, grassTiles, groundSortingOrder, col, row);
                    continue;
                }

                // Sample Perlin noise for this cell
                float dirtNoise  = Mathf.PerlinNoise(col * dirtNoiseScale,  row * dirtNoiseScale);
                float decorNoise = Mathf.PerlinNoise(
                    col * decorNoiseScale + decorNoiseOffset,
                    row * decorNoiseScale + decorNoiseOffset);

                // Dirt patch?
                if (dirtNoise > (1f - dirtThreshold) && dirtTiles != null && dirtTiles.Count > 0)
                {
                    SpawnTileFromList(worldPos, dirtTiles, groundSortingOrder, col, row);
                    // No decoration on dirt — looks cleaner
                    continue;
                }

                // Grass base
                SpawnTileFromList(worldPos, grassTiles, groundSortingOrder, col, row);

                // Decoration on top?
                if (decorNoise > (1f - decorThreshold) && decorationTiles != null && decorationTiles.Count > 0)
                {
                    SpawnTileFromList(worldPos, decorationTiles, decorSortingOrder, col, row);
                }
            }
        }

        Debug.Log($"[WorldGenerator] World generated — {grid.Columns}×{grid.Rows} cells.");
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /// <summary>
    /// Picks a weighted-random tile from the list and spawns it at worldPos.
    /// Does nothing if the list is null or empty.
    /// </summary>
    private void SpawnTileFromList(Vector3 worldPos, List<TileData> list, int sortingOrder, int col, int row)
    {
        if (list == null || list.Count == 0) return;

        TileData tile = PickWeighted(list);
        if (tile == null || tile.sprite == null) return;

        SpawnTile(worldPos, tile, sortingOrder, col, row);
    }

    /// <summary>
    /// Weighted random selection. Each TileData's weight is its share of the total weight sum.
    /// </summary>
    private TileData PickWeighted(List<TileData> tiles)
    {
        int totalWeight = 0;
        foreach (var t in tiles)
            if (t != null) totalWeight += t.weight;

        if (totalWeight == 0) return tiles[0];

        int roll = Random.Range(0, totalWeight);
        int running = 0;
        foreach (var t in tiles)
        {
            if (t == null) continue;
            running += t.weight;
            if (roll < running) return t;
        }
        return tiles[0];
    }

    /// <summary>
    /// Instantiates the tile prefab, assigns the sprite, and scales it to fit the cell exactly.
    /// </summary>
    private void SpawnTile(Vector3 worldPos, TileData tile, int sortingOrder, int col, int row)
    {
        GameObject go = Instantiate(tilePrefab, worldPos, Quaternion.identity, _tileParent);
        go.name = $"Tile_{col}_{row}_{tile.tileName}";

        var sr = go.GetComponent<SpriteRenderer>();
        if (sr == null)
        {
            Debug.LogError("[WorldGenerator] tilePrefab has no SpriteRenderer component!");
            Destroy(go);
            return;
        }

        sr.sprite       = tile.sprite;
        sr.sortingOrder = sortingOrder;

        // Scale the tile so it fills exactly one grid cell.
        // Sprite size in world units = sprite.bounds.size (at PPU set on import).
        // We want the tile to be CellSize × CellSize world units.
        float spriteWorldSize = tile.sprite.bounds.size.x; // assumes square tiles
        if (spriteWorldSize > 0f)
        {
            float scale = WorldGrid.Instance.CellSize / spriteWorldSize;
            go.transform.localScale = new Vector3(scale, scale, 1f);
        }
    }
}
